version: "3.9"

services:
  database_fazendasavenda:
    image: postgres
    container_name: database_fazendasavenda
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fazendasavenda
      - POSTGRES_PASSWORD=fazendasavenda
      - POSTGRES_DB=fazendasavenda
    volumes:
      - pgdata:/data/postgres

  api:
    build: .
    image: node
    container_name: api_fazendasavenda
    ports:
      - 3333:3333
    volumes:
      - .:/usr/fazendasavenda
    links:
      - database_fazendasavenda
    depends_on:
      - database_fazendasavenda


volumes:
  pgdata:
    driver: local
